import { PortfolioData } from "./types";

export const initialPortfolioData: PortfolioData = {
  profile: {
    id: "a0000000-0000-0000-0000-000000000001",
    full_name: "Dhanush Rao",
    tagline: "WebGL & Cloud Architect",
    bio: "Pioneering modern interactive web applications combining WebGL, Next.js, and cloud backends. Passionate about performant design systems, fluid micro-interactions, and reactive interfaces.",
    avatar_url: "/avatars/male-1.png",
    resume_file_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    status_badge: "Open to High-Impact Leadership Roles",
    social_links: {
      github: "https://github.com",
      linkedin: "https://linkedin.com",
      twitter: "https://twitter.com",
      instagram: "https://instagram.com",
    },
    updated_at: new Date().toISOString(),
  },
  skills: [
    {
      id: "s1",
      name: "TypeScript / JS",
      category: "language",
      icon_url: "https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg",
      proficiency_level: 96,
      order_index: 1,
      is_visible: true,
    },
    {
      id: "s2",
      name: "Three.js & WebGL",
      category: "language",
      icon_url: "https://raw.githubusercontent.com/devicons/devicon/master/icons/threejs/threejs-original.svg",
      proficiency_level: 92,
      order_index: 2,
      is_visible: true,
    },
    {
      id: "s3",
      name: "Next.js 15 & React",
      category: "tool",
      icon_url: "https://raw.githubusercontent.com/devicons/devicon/master/icons/nextjs/nextjs-original.svg",
      proficiency_level: 98,
      order_index: 3,
      is_visible: true,
    },
    {
      id: "s4",
      name: "PostgreSQL & Supabase",
      category: "database",
      icon_url: "https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original.svg",
      proficiency_level: 90,
      order_index: 4,
      is_visible: true,
    },
    {
      id: "s5",
      name: "Redis & In-Memory DB",
      category: "database",
      icon_url: "https://raw.githubusercontent.com/devicons/devicon/master/icons/redis/redis-original.svg",
      proficiency_level: 86,
      order_index: 5,
      is_visible: true,
    },
    {
      id: "s6",
      name: "Docker & Cloud Native",
      category: "tool",
      icon_url: "https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original.svg",
      proficiency_level: 88,
      order_index: 6,
      is_visible: true,
    },
    {
      id: "s7",
      name: "Distributed Architecture",
      category: "soft_skill",
      icon_url: "",
      proficiency_level: 94,
      order_index: 7,
      is_visible: true,
    },
    {
      id: "s8",
      name: "Design Systems & Motion",
      category: "soft_skill",
      icon_url: "",
      proficiency_level: 92,
      order_index: 8,
      is_visible: true,
    },
  ],
  work_experience: [
    {
      id: "w1",
      role: "Lead Frontend Architect",
      company: "HyperSphere Interactive",
      location: "San Francisco, CA (Remote)",
      start_date: "2023",
      end_date: "Present",
      is_current: true,
      description: "Spearheaded real-time 3D collaboration canvas handling 100k+ MAU with 60 FPS WebGL rendering. Reduced bundle size by 42% and implemented modular micro-frontend design system.",
      certificate_url: "",
      order_index: 1,
      is_visible: true,
    },
    {
      id: "w2",
      role: "Senior Full-Stack Engineer",
      company: "Vortex Cloud Labs",
      location: "New York, NY",
      start_date: "2021",
      end_date: "2023",
      is_current: false,
      description: "Directed migration to Next.js App Router and PostgreSQL read-replicas. Engineered distributed caching cluster reducing latency by 68%.",
      certificate_url: "",
      order_index: 2,
      is_visible: true,
    },
    {
      id: "w3",
      role: "Creative 3D Web Developer",
      company: "Studio Nebula",
      location: "Seattle, WA",
      start_date: "2019",
      end_date: "2021",
      is_current: false,
      description: "Developed award-winning 3D web applications, interactive product visualizers, and procedural WebGL animations for Tier-1 clients.",
      certificate_url: "",
      order_index: 3,
      is_visible: true,
    },
  ],
  education: [
    {
      id: "e1",
      institution: "Stanford University",
      degree: "M.S. in Computer Science (Graphics & Systems)",
      score_or_cgpa: "3.95 / 4.00 CGPA",
      start_year: "2017",
      end_year: "2019",
      description: "Graduate coursework in hardware-accelerated shaders, GPU parallel computing, and distributed database consistency.",
      order_index: 1,
      is_visible: true,
    },
    {
      id: "e2",
      institution: "University of Washington",
      degree: "B.S. in Software Engineering",
      score_or_cgpa: "3.88 / 4.00 CGPA",
      start_year: "2013",
      end_year: "2017",
      description: "Summa Cum Laude. ACM SIGGRAPH President and Undergraduate Teaching Fellow for Object-Oriented Design.",
      order_index: 2,
      is_visible: true,
    },
  ],
  certificates_achievements: [
    {
      id: "c1",
      title: "AWS Certified Solutions Architect - Professional",
      issuer: "Amazon Web Services",
      issue_date: "Nov 2024",
      credential_url: "https://aws.amazon.com/verification",
      certificate_file_url: "",
      lor_loa_urls: [
        { label: "Verification Transcript", url: "https://aws.amazon.com/verification" },
        { label: "Letter of Commendation", url: "https://example.com/lor.pdf" }
      ],
      type: "certificate",
      order_index: 1,
      is_visible: true,
    },
    {
      id: "c2",
      title: "Awwwards Site of the Day & Developer Award",
      issuer: "Awwwards Official Jury",
      issue_date: "Aug 2024",
      credential_url: "https://www.awwwards.com",
      certificate_file_url: "",
      lor_loa_urls: [],
      type: "award",
      order_index: 2,
      is_visible: true,
    },
    {
      id: "c3",
      title: "Google Cloud Professional Cloud Architect",
      issuer: "Google Cloud",
      issue_date: "Jan 2024",
      credential_url: "https://cloud.google.com/certification",
      certificate_file_url: "",
      lor_loa_urls: [],
      type: "certificate",
      order_index: 3,
      is_visible: true,
    },
    {
      id: "c4",
      title: "Disrupt Global Hackathon First Place Champion",
      issuer: "TechCrunch Disrupt",
      issue_date: "Oct 2023",
      credential_url: "https://techcrunch.com",
      certificate_file_url: "",
      lor_loa_urls: [{ label: "Official Winner Release", url: "https://techcrunch.com" }],
      type: "merit",
      order_index: 4,
      is_visible: true,
    },
  ],
  projects: [
    {
      id: "p1",
      title: "Aether 3D Engine & Spatial Canvas",
      short_description: "Interactive WebGL spatial canvas with real-time physics and procedural particle systems.",
      long_description: "Aether is an advanced 3D spatial computing playground built on Three.js and custom GLSL shaders. Features dynamic physics simulation, audio reactivity, and GPU-driven procedural particle ribbons.",
      cover_image_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
      demo_link: "https://threejs.org",
      github_link: "https://github.com",
      tech_stack: ["Three.js", "WebGL", "TypeScript", "GLSL Shaders"],
      featured: true,
      order_index: 1,
      is_visible: true,
    },
    {
      id: "p2",
      title: "Nova Quantum Telemetry Dashboard",
      short_description: "Real-time financial telemetry dashboard with streaming WebSocket analytics.",
      long_description: "Nova provides high-frequency analytics streaming for decentralized liquidity protocols. Includes custom charting engine, glassmorphic UI, and multi-tenant security.",
      cover_image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
      demo_link: "https://nextjs.org",
      github_link: "https://github.com",
      tech_stack: ["Next.js 15", "PostgreSQL", "WebSocket", "TailwindCSS"],
      featured: true,
      order_index: 2,
      is_visible: true,
    },
    {
      id: "p3",
      title: "HyperStore Headless 3D Commerce",
      short_description: "Ultra-fast 3D product visualizer with instant augmented reality checkout.",
      long_description: "Next-generation commerce experience allowing customers to inspect 3D models with ray-marched reflections in their browser, customize colorways in real time, and check out seamlessly.",
      cover_image_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
      demo_link: "https://stripe.com",
      github_link: "https://github.com",
      tech_stack: ["React", "Supabase", "Stripe", "Three.js"],
      featured: false,
      order_index: 3,
      is_visible: true,
    },
  ],
};
